/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainGUI.java
 *
 * Created on Nov 3, 2014, 2:21:32 PM
 */
package cmpt305_swingmvc_lohnerb3;

import java.awt.event.ActionListener;
import javax.swing.JTable;

/**
 *
 * @author User
 */
public class MainGUI extends javax.swing.JFrame {

    /** Creates new form MainGUI */
    public MainGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public JTable getContactTable() {
        return contactTable;
    }
    
    public void clearInfoDisplay() {
        infoDisplay.setText("");
    }
    
    public void setInfoDisplay(String info) {
        infoDisplay.setText(info);
    }
    
    public void setEnabledDeleteButton(boolean status) {
        deleteContactButton.setEnabled(status);
    }
    
    public void addNewContactButtonListener(ActionListener al) {
        newContactButton.addActionListener(al);
    }
    
    public void addDeleteButtonListener(ActionListener al) {
        deleteContactButton.addActionListener(al);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        newContactButton = new javax.swing.JButton();
        deleteContactButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        tableScrollPane = new javax.swing.JScrollPane();
        contactTable = new javax.swing.JTable();
        infoScrollPane = new javax.swing.JScrollPane();
        infoDisplay = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Address Book");
        setName("MainGUIFrame"); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        newContactButton.setText("New Contact");
        newContactButton.setToolTipText("adds new contact");
        newContactButton.setFocusable(false);
        newContactButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newContactButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newContactButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(newContactButton);

        deleteContactButton.setText("Delete");
        deleteContactButton.setToolTipText("deletes contact");
        deleteContactButton.setFocusable(false);
        deleteContactButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteContactButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteContactButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(deleteContactButton);

        jSplitPane1.setDividerSize(10);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.5);

        contactTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        contactTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableScrollPane.setViewportView(contactTable);

        jSplitPane1.setTopComponent(tableScrollPane);

        infoDisplay.setEditable(false);
        infoDisplay.setColumns(20);
        infoDisplay.setRows(5);
        infoScrollPane.setViewportView(infoDisplay);

        jSplitPane1.setRightComponent(infoScrollPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void deleteContactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteContactButtonActionPerformed

}//GEN-LAST:event_deleteContactButtonActionPerformed

private void newContactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newContactButtonActionPerformed

}//GEN-LAST:event_newContactButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable contactTable;
    private javax.swing.JButton deleteContactButton;
    private javax.swing.JTextArea infoDisplay;
    private javax.swing.JScrollPane infoScrollPane;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton newContactButton;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
}
